sudo: false
language: node_js
node_js:
  - "8"
env:
  global:
    - ALIAS=mcs-lite-app.now.sh
    - TEAM=mcs-lite

branches:
  only:
  - master

before_script:
  - npm install -g now now-purge await-url

script:
  # - echo "TODO: test"

after_success:
  # 0. Use team
  - now switch $TEAM --token $NOW_TOKEN

  # 1. Wair for deployment ready
  - URL=$(now --public --token $NOW_TOKEN)
  - await-url $URL
  - now ls mcs-lite-app-demo --token $NOW_TOKEN

  # 2. Alias and purge
  - now alias set "$URL" "$ALIAS" --token $NOW_TOKEN
  - now-purge -t $NOW_TOKEN --team $TEAM

  # 3. Scale to 1
  - now scale $ALIAS 1 --token $NOW_TOKEN

notifications:
  email: evenchange4@gmail.com
